### ISSUE TITLE
Is there any update?

### ISSUE THREAD

**Issue by l1teng** [ydzhou-pku/A-night-time-outdoor-data-set-for-low-light-enhancement#1]
Hi, zhou,

I'd like to know if the data is uploaded. I did not check any data in this repo.

Best wishes.

--
Teng Li

**Comment by ydzhou-pku** [comment]
您好，
&nbsp; &nbsp; &nbsp; &nbsp; 感谢您的来信，我最近忙于论文和工作，但已经准备好了数据集的上传，将会在最近更新，请您再耐心等待一两天，造成不便的话，还请您体谅。


此致
敬礼



发自我的iPhone


------------------ Original ------------------
From: Teng Li ***@***.***&gt;
Date: Sun,May 9,2021 3:48 AM
To: ydzhou-pku/A-night-time-outdoor-data-set-for-low-light-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ydzhou-pku/A-night-time-outdoor-data-set-for-low-light-enhancement] Is there any update? (#1)

**Comment by ydzhou-pku** [comment]
Dear Li,

Link on Baidu Netdisk will be uploaded in the next two days. Really appreciate your attention and understanding.

Yours,
Zhou.

**Comment by l1teng** [comment]
> 您好， &nbsp; &nbsp; &nbsp; &nbsp; 感谢您的来信，我最近忙于论文和工作，但已经准备好了数据集的上传，将会在最近更新，请您再耐心等待一两天，造成不便的话，还请您体谅。 此致 敬礼 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Teng Li ***@***.***&gt; Date: Sun,May 9,2021 3:48 AM To: ydzhou-pku/A-night-time-outdoor-data-set-for-low-light-enhancement ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [ydzhou-pku/A-night-time-outdoor-data-set-for-low-light-enhancement] Is there any update? (#1)

Thanks for your reply. 

Sorry for disturbing you and look forward to your new work.

Best wishes. 

--

Teng Li
